### ISSUE TITLE
How to integrate new database support?

### ISSUE THREAD

**Issue by MobileAppVault** [hashedin/squealy#227]
Hi, 

nice project! Can you provide a documentation on how we can integrate a new database support.

Want to test it with ORACLE and MSSQL. 👍 

Many Thanks!

**Comment by swapnil95** [comment]
You need to understand these two things to integrate a new database support for ORACLE and MSSQL

## Database configuration in Django

You can go through [this](https://docs.djangoproject.com/en/1.11/ref/settings/#databases) section in 
Django's documentation to understand how database setup is done in Django. 

## Configuring database backend for ORACLE and MSSQL

**ORACLE** database can easily be configured since django provides support for that. You can follow [these](https://www.webforefront.com/django/setupdjangodatabase.html) steps to configure your ORACLE database.

For **MSSQL**, you will have to use a third party library which provides a database engine for MSSQL. Here are a couple of popular libraries which can be used to configure MSSQL database - [django-pyodbc-azure](https://pypi.python.org/pypi/django-pyodbc-azure) and [django-mssql](http://django-mssql.readthedocs.io/en/latest/quickstart.html)

Hope this is helpful
